### PR TITLE
127-error-in-tcplhit2_core-processing-invitrodb-level-5-for-tox21

### LINKED ISSUE #127: Error in tcplhit2_core processing invitrodb level 5 for tox21
`tcplhit2_core` is failing:
`Error in if (hitcall > 0) { : missing value where TRUE/FALSE needed` 
on line:
https://github.com/USEPA/CompTox-ToxCast-tcplFit2/blob/3b302bdaf95dadb83f5a50084d25940971d438fa/R/tcplhit2_core.R#L160
while processing one specific row of data at level 5 for invitrodb tox21 reprocessing. Hitcall is NA. This might be as simple as including `is.na` in https://github.com/USEPA/CompTox-ToxCast-tcplFit2/blob/3b302bdaf95dadb83f5a50084d25940971d438fa/R/tcplhit2_core.R#L154-L156
unless hitcall is not meant to be NA here, and there's either user error or hitcall logic error somewhere before.

Reproducible example:
```
devtools::load_all(".") # load tcplfit2
load("example.rda") # file cannot be uploaded github so can send over teams
tcplhit2_core(params = examplerda$params, 
              conc = examplerda$conc, 
              resp = examplerda$resp, 
              bmed = examplerda$bmed, 
              cutoff = examplerda$cutoff, 
              onesd = examplerda$onesd, 
              bmd_low_bnd = .1, 
              bmd_up_bnd = 10)
```

### PR DESCRIPTION
**Pull request by knuppla**
Add additional argument to `acy()` to provide top location before additional checks are made. Will eventually need to investigate why similar behavior is not occurring on line 119 of `tcplfit2_core`. 

Will close #127 

4/9/25 EDIT: Created new utility function called 'calcempirical' that calculates the "top" and "xtop" empirically. Included 'verbose' as argument to functions to inform users empirical calculations are being used. Ran roxygen2::roxygenise() to update documentation files.

### CODE REVIEW

File: R/hitcontinner.R [hunk 1]
```diff
@@ -20,6 +20,7 @@
 #'   supported distribution is "dnorm", the normal distribution.
 #' @param poly2.biphasic Which fitting method to use for poly2. If poly2.biphasic = TRUE, allows for biphasic polynomial 2
 #'   model fits (i.e. both monotonic and non-monotonic). (Defaults to TRUE.)
+#' @param verbose If verbose = TRUE, will print status of empirical calculations.
```
Comment (sedavid01) [inline R/hitcontinner.R]: What is the default?

File: R/tcplfit2_core.R [hunk 2]
```diff
@@ -12,7 +12,7 @@
 #'   force.fit = FALSE, will only fit constant model.
 #' @param force.fit If force.fit = TRUE, will fit all models regardless of cutoff.
 #' @param bidirectional If bidirectional = FALSE, will only give positive fits.
-#' @param verbose If verbose = TRUE, will print optimization details and aics.
+#' @param verbose If verbose = TRUE, will print optimization details, aics, and status of empirical calculations.
```
Comment (sedavid01) [inline R/tcplfit2_core.R]: What is the default?

File: R/tcplhit2_core.R [hunk 3]
```diff
@@ -34,6 +34,7 @@
 #'   censored and shifted left.
 #' @param poly2.biphasic If poly2.biphasic = TRUE, allows for biphasic polynomial 2
 #'   model fits (i.e. both monotonic and non-monotonic). (Defaults to TRUE.)
+#' @param verbose If verbose = TRUE, will print status of empirical calculations.
```
Comment (sedavid01) [inline R/tcplhit2_core.R]: What is the default?

File: R/toplikelihood.R [hunk 4]
```diff
@@ -20,7 +20,8 @@
 #'   supported distribution is "dnorm", the normal distribution.
 #' @param poly2.biphasic Which fitting method to use for poly2. If poly2.biphasic = TRUE, allows for biphasic polynomial 2
 #'   model fits (i.e. both monotonic and non-monotonic). (Defaults to TRUE.)
-#'
+#' @param verbose If verbose = TRUE, will print status of empirical calculations.
```
Comment (sedavid01) [inline R/toplikelihood.R]: What is the default?

File: R/toplikelihood.R [hunk 5]
```diff
@@ -73,6 +74,10 @@ toplikelihood = function(fname, cutoff, conc, resp, ps, top, mll, errfun = "dt4"
       ps[1] = cutoff
     } else {
       x_top = acy(y = top, modpars = list(tp=ps[1],ga=ps[2],p=ps[3],la=ps[4],q=ps[5],er=ps[6]), type = fname)
+      if (is.na(x_top)) { # NA is returned for x_top, find empirical x_top
+        if (verbose) warning("NA returned for x_top in function toplikelihood, finding empirical x_top")
```
Comment (sedavid01) [inline R/toplikelihood.R]: May just clarify that "NA returned for analytical x_top (i.e. when gnls derivative = 0) in ...". Or something like this to provide more specific context.

File: R/calcempirical.R [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+#'    \item x_top - concentration at which empirical top occurs
+#'  }
+#' @export
+#'
+#' @examples
+#' conc = c(.03,.1,.3,1,3,10,30,100)
+#' ps = c(1,2,1,2,2)
+#' fname = "gnls"
+#' calcempirical(conc, ps, fname)
+calcempirical = function(conc, ps, fname) {
```
Comment (sedavid01) [inline R/calcempirical.R]: May also go ahead and add an argument for altering the level of precision since this is an exported function for users.  Default length of sampling points within the experimental concentration range can be set to 100.

File: R/calcempirical.R [hunk 7]
```diff
@@ -0,0 +1,37 @@
+#' Empirically locate top and top concentration
+#'
+#' Locate the top and the concentration at which top occurs empirically by sampling points from the experimental concentration values.
```
Comment (sedavid01) [inline R/calcempirical.R]: "sampling points within the experimental concentration range"  or some other slight rewording.  Currently reads a little too close to estimating top using on the experimental concentrations themselves.  I know that is not what you mean but want to ensure additional clarification.

File: R/calcempirical.R [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+#' calcempirical(conc, ps, fname)
+calcempirical = function(conc, ps, fname) {
+
+  # replace untreated controls with pseudo-value
+  if (any(conc == 0)) warning("Data contains untreated controls (conc = 0). A pseudo value replaces -Inf after log-transform.  The pseudo value is set to one log-unit below the lowest experimental `conc`.")
+
+  logc <- log10(conc)
+  logc_temp <- replace(logc, logc == -Inf, sort(unique(logc)[2]-1))
+  # generate concentration sequence over entire experimental concentration range
+  conc_seq <- 10**seq(from = min(logc_temp), to = max(logc_temp), length.out = 100)
```
Comment (sedavid01) [inline R/calcempirical.R]: I am curious why "**" is used for exponentiation rather than "^". Can keep it since it should provide the same output.

File: R/calcempirical.R (hunk 6 above)
Comment (sedavid01) [inline R/calcempirical.R]: May also consider calling it "calcempirical_top" just to be clear since there may be other empirical estimations/calculations we need to make in future.

**Review by sedavid01 — CHANGES_REQUESTED** [review]
There are some minor requested changes, but overall the updates look good as well as the testing results.

@cthunes, when you get a chance can you please test this update on your end.

**Review by sedavid01 — APPROVED** [review]
I am approving the updates in this PR.  Though the branch should not be merged until we have confirmation from @cthunes (i.e. PR approval) indicating no further issues with recent updates.

**Review by cthunes — APPROVED** [review]
tcpl processing with this branch was successful. It did run overnight before this morning's minor updates, but it appears these updates (with all function names seemingly updated), shouldn't affect the result. Thank you!

**Comment by sedavid01** [comment]
All approvals are in. Merging PR with 'dev'.
